name: Chen Qiming
url: Qiming-Chen.github.io
description: good good study,day day upï¼

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['Gemfile.lock', 'Gemfile', 'Rakefile']
